const standardColor = {
	red: '#e54d42',
	orange: '#f37b1d',
	yellow: '#fbbd08',
	olive: '#8dc63f',
	green: '#39b54a',
	cyan: '#1cbbb4',
	blue: '#0081ff',
	purple: '#6739b6',
	mauve: '#9c26b0',
	pink: '#e03997',
	brown: '#a5673f',
	grey: '#8799a3',
	black: '#333333',
	darkGray: '#666666',
	gray: '#aaaaaa',
	ghostWhite: '#f1f1f1',
	white: '#ffffff',
}

const lightColor = {
	redLight: '#fadbd9',
	orangeLight: '#fde6d2',
	yellowLight: '#fef2ce',
	oliveLight: '#e8f4d9',
	greenLight: '#d7f0db',
	cyanLight: '#d2f1f0',
	blueLight: '#e7f7fc',
	purpleLight: '#e1d7f0',
	mauveLight: '#ebd4ef',
	pinkLight: '#f9d7ea',
	brownLight: '#ede1d9',
	greyLight: '#e7ebed',
}

export default {
	'default': {
		theme: 'default',
		emphasizeColor: '#f08A00',
		commonColor: '#ffffff',
		navigationBarBackgroundColor: '#f08A00',
		navigationBarTextColor: '#ffffff',
		navigationBarHighlightColor: '#ffffff',
		chartItemStyle: '#fda52f',
		chartAreaStyle: '#fde6d2',
		standardColor: standardColor,
		lightColor: lightColor,
	},
	'darkColor': {
		theme: 'darkColor',
		emphasizeColor: '#70c8e2',
		commonColor: '#ffffff',
		navigationBarBackgroundColor: '#70c8e2',
		navigationBarTextColor: '#ffffff',
		navigationBarHighlightColor: '#ffffff',
		chartItemStyle: '#70c8e2',
		chartAreaStyle: '#f5f8fd',
		standardColor: standardColor,
		lightColor: lightColor,
	},
	'lightColor': {
		theme: 'lightColor',
		emphasizeColor: '#70c8e2',
		commonColor: '#ffffff',
		navigationBarBackgroundColor: '#ffffff',
		navigationBarTextColor: '#000000',
		navigationBarHighlightColor: '#000000',
		chartItemStyle: '#70c8e2',
		chartAreaStyle: '#f5f8fd',
		standardColor: standardColor,
		lightColor: lightColor,
		
	}
}
